### PR TITLE
Add SRFI 175

### PR DESCRIPTION
**Pull request by lassik**
This is the sample implementation at the time the SRFI was finalized.

### CODE REVIEW

**Comment by leppie** [comment]
Can this be 'namespaced' too? ie `(srfi :175 ascii)` and use the same existing stucture?

While I dont use it, I am sure some scheme's have some autocomplete thing for libraries.

**Comment by lassik** [comment]
The R7RS convention is to just use `(import (srfi 175))`. Is the named R6RS convention `(import (srfi :175 ascii))` widespread, and has it been standardized somewhere? [SRFI 97](https://srfi.schemers.org/srfi-97/srfi-97.html) has some names but is quite old.

**Comment by lassik** [comment]
Also, is the R6RS convention to have _both_ of the following library names available, so people can pick whichever one they like?

* `(import (srfi :175))`
* `(import (srfi :175 ascii))`

If this is the usual way to do it, I'll accommodate, though it's nice if the standard set of library names is tracked somewhere.

**Comment by leppie** [comment]
> Also, is the R6RS convention to have _both_ of the following library names available, so people can pick whichever one they like?

If you look at the general pattern, it looks like it, even for simple libraries. 

Maybe @arcfide can chime in :D

**Comment by leppie** [comment]
I also dont know if this need to be added to the registry/compile files 

https://github.com/arcfide/chez-srfi/blob/master/private/registry.sls

**Comment by lassik** [comment]
If people have kept inventing and using new names long after SRFI 97 was published, we should probably keep doing it also for new SRFIs, but it would be best to collect the names in some up-to-date central place. @arthurgleckler, the SRFI editor, may be willing to maintain such a list as long as the technical approach is simple. We had some talks earlier this year about maintaining some other low-maintenance identifier lists like that - I can't remember the exact details right now, but if a new entry is added to the list every month or so then the amount of work is minimal. We should ask him early January.

**Comment by lassik** [comment]
There's a policy to not give any SRFI generic, numberless import names like `(srfi arrays)` because a later SRFI might specify a competing array interface that some people like better. But since the R6RS names also contain the SRFI number it should be all right.

**Comment by leppie** [comment]
> There's a policy to not give any SRFI generic, numberless import names like `(srfi arrays)` because a later SRFI might specify a competing array interface that some people like better. But since the R6RS names also contain the SRFI number it should be all right.

Yeah, for this repo, the name is never 'top level', so just 'sub-namespacing' is safe implicitly.

**Comment by arcfide** [comment]
This repo uses the ASCII sub-names for almost everything I've seen, and I agree that it's nice to have in their. This was done at first, I think, to provide for better auto-import on some systems. I think it would be good to keep it in and expand the practice. You can see the other repository examples to see the pattern.

**Comment by lassik** [comment]
The `registry.sls` in this repo is a nice list. We could send that to Arthur to use as a basis for an official list.

**Comment by arthurgleckler** [comment]
We could add them as attributes in [srfi-data.scm](https://github.com/scheme-requests-for-implementation/srfi-common/blob/master/admin/srfi-data.scm).  Lassi, would you like to send me a pull request?

**Comment by lassik** [comment]
Great idea! Will do.

**Pull request merged**
