### PR TITLE
add [SRFI-171] implementation

### PR DESCRIPTION
**Pull request by wttr893**
Implementation and test are adapted from Linus Björnstam's work[1].

[1] https://hg.sr.ht/~bjoli/guile-srfi-171

### CODE REVIEW

**Comment by wttr893** [comment]
I am new to scheme and Chez. There may be some unidomatic things in here. Please let me know if anything needs to be changed.

**Comment by arcfide** [comment]
Thanks for the commit! If you can just fix up the issue with the test suite to ensure that things are working in the CI tests, that would be great. Otherwise, I think this looks good.

**Comment by arcfide** [comment]
Sorry, the checks are still failing.

**Comment by wttr893** [comment]
The tests were passing in my repl but there must be something different about that environment and where the tests run for CI.

I set up the soft links and ran test_all.sh just like the CI action. It does work on my machine, but there might still be differences with the CI environment.

**Pull request merged**
