### PR TITLE
Compatibility fixes for Guile

### PR DESCRIPTION
**Pull request by weinholt**
Please consider merging these changes that I made while porting Akku.scm to Guile. See the commit message for more details.

The libraries don't work out of the box with Guile, but the next release of Akku rewrites the library names so that everything works as it should.

### CODE REVIEW

**Comment by arcfide** [comment]
Thanks for this submission! I think I like most of what I see here. However, in regexp.scm you have changed the formatting of some of the files to a non-standard formatting, is there a good reason for doing this? Otherwise, I do not think that these changes are likely to break any other implementations and so they are fine for bringing in.

**Comment by weinholt** [comment]
The formatting change is a workaround for Guile bug#31864, wherein Guile can't read R6RS hex escapes in symbols. The workaround isn't great really, but it does mean that Guile can use that library (except for that symbol). I think the developers are really busy with other things right now, but future Guile versions should read the symbols correctly. I could instead add a Guile-specific version of the library that uses Guile's native symbol syntax instead of the R6RS syntax. What do you think?

I don't have access to the right computer now (on vacation), but I think that sometime after submitting this PR, I found that the `define-values` implementation in chez-srfi/private doesn't work on Guile. Guile has a native `define-values` that can be used instead.

I can update the PR in a few days when I'm back from my trip. But I was wondering what your thoughts are about adding support for more implementations. The project is called chez-srfi, you don't mind getting PRs like this?

**Comment by arcfide** [comment]
I think it would be good to have the updated library to include the `define-values` fix. I think I would prefer to accept the stranger formatting rather than adding a whole new library for Guile. 

I am not opposed to adding support for more implementations if this library has somehow become a source for people, but my main requirement is that any of the patches I make to this library or that I accept from other people should not break the Chez support, as that is still the primary target of this library.

**Comment by arcfide** [comment]
Okay, this does not look like it should cause any troubles elsewhere, so I am going to merge it in. Thanks for the contribution!

**Pull request merged**
