### PR TITLE
Corrected bugs and optimized (srfi :126 r6rs-hashtables)

### PR DESCRIPTION
**Pull request by jessymilare**
- make-hashtable must accept #f as hash procedure when equiv is eq? or eq?;
- make-hashtable must accept a pair of hash procedures or a single procedure;
- weakness argument of make-hashtable was not tested in Chez Scheme.
    Instead, Chez Scheme now signals an error if weakness is neither weak-key
    nor ephemeral-key (when version >= 9.5.0);
- avoids consing lists in hashtable-sum and hashtable-map->lset;
- hashtable-intern! uses hashtable-cell when available (only Chez Scheme
    supports that for now).

### CODE REVIEW

**Comment by arcfide** [comment]
Thanks for this. Nothing jumps out at me as too heinous in this, and I agree it would be good to ensure that the code matches up better with the correct specifications. Assuming that this doesn't break any other implementations I'm good to go.

**Comment by jessymilare** [comment]
One issue found: I just found out that ikarus does not implement equal-hash. The reason is that it is "too slow":

https://answers.launchpad.net/ikarus/+faq/276

What a lame excuse. If one uses equal-hash, it's obvious one is aware of that limitation. That's standard, for love sake!

Anyway, all tests besides the ones using equal-hash work.

**Comment by jessymilare** [comment]
Fixed two issues with ikarus: created a test-file that doesn't use equal-hash, and also changed the implementation of hashtable-clear! (ikarus doesn't support two arguments for hashtable-clear!, despite this also being standard).

I'll try larceny now.

**Comment by jessymilare** [comment]
Larceny tests work. Larceny doesn't expose the eq-hash-function anymore, so we can suppress the note at the end of the file.

jessica@jessica-pc:~/Dev/larceny-1.3-bin-native-ia32-linux86$ ./larceny -r7r6 -I /home/jessica/Dropbox/Scheme/
Larceny v1.3 "Grain Alcohol and Rainwater" (Aug  6 2017 01:16:30, precise:Linux:unified)
larceny.heap, built on Sun Aug  6 01:16:56 EDT 2017

> (import (srfi :126))

>  (load "/home/jessica/Dropbox/Scheme/srfi/tests/r6rs-hashtables.sps")
%%%% Starting test SRFI-126
# of expected passes      186

NOTE: On implementations using the (r6rs hashtables) library from Larceny,
      14 tests are expected to fail in relation to make-eq-hashtable and
      make-eqv-hashtable returning hashtables whose hash functions are
      exposed instead of being #f.  We have no obvious way to detect this
      within this portable test suite, hence no XFAIL results.

**Comment by arcfide** [comment]
Okay, lack of standard functions in an implementation isn't very good, but this is good enough for me. :-) I'll merge this in.

**Pull request merged**
