### PR TITLE
Renamed .scm when it had a search order conflict with .sls

### PR DESCRIPTION
**Pull request by weinholt**
SRFIs 14, 26, 64 and 115 had .scm files that conflict with the
matching .sls file when an implementation's library extension list
has .scm before .sls.

### CODE REVIEW

**Comment by arcfide** [comment]
Is there a reason that SRFIs 26 and 64 had their file names changed to the numbers, while SRFIs 14 and 115 just had `-impl` inserted into their name?

**Comment by weinholt** [comment]
No reason, it has no significance. I just looked at the individual parts and didn't then examine the whole change. I can change it to be consistent, if you prefer one style over the other?

**Comment by arcfide** [comment]
I prefer the "meaningful" names to the SRFI numbers, personally, and I like to have it more consistent, so if you wouldn't mind changing that, I would prefer it before I merge this in. Otherwise, good catch!

**Comment by weinholt** [comment]
Thanks. I have changed the names and tested that import still works.

**Comment by arcfide** [comment]
Thanks!

**Pull request merged**
